// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnsZhRFnm2qF2PNG_cf0ZpvqiL1SerFYg',
    appId: '1:401187447883:web:48ae08ee01630ddb6b99ce',
    messagingSenderId: '401187447883',
    projectId: 'spend-wise-1acfb',
    authDomain: 'spend-wise-1acfb.firebaseapp.com',
    storageBucket: 'spend-wise-1acfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQJaXD-vSHkT98QpaVIfpwyglfzVCSBig',
    appId: '1:401187447883:android:fef6a20649e984b36b99ce',
    messagingSenderId: '401187447883',
    projectId: 'spend-wise-1acfb',
    storageBucket: 'spend-wise-1acfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx58WvvqXtTnveCZ3xoa48GJ_3GejbHjQ',
    appId: '1:401187447883:ios:b575412ec8a3dc4b6b99ce',
    messagingSenderId: '401187447883',
    projectId: 'spend-wise-1acfb',
    storageBucket: 'spend-wise-1acfb.appspot.com',
    iosBundleId: 'com.example.spendWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx58WvvqXtTnveCZ3xoa48GJ_3GejbHjQ',
    appId: '1:401187447883:ios:8deb5aceaff5c6686b99ce',
    messagingSenderId: '401187447883',
    projectId: 'spend-wise-1acfb',
    storageBucket: 'spend-wise-1acfb.appspot.com',
    iosBundleId: 'com.example.spendWise.RunnerTests',
  );
}
